### PR TITLE
Completely reorganized and updated

### PR DESCRIPTION
**Pull request by joefowler**
I’ve completed my plan to reorganize, modernize, and document the functions in this package. I have 4 categories of functions now:

1. Robust location estimators
2. Robust dispersion estimators
3. Confidence interval and standard error estimates for the statistics in categories 1 and 2.
4. “Unmaintained” functions. Normal people would probably just toss all of this in the trash, but I don’t consider myself enough of an expert in robust statistics to judge. The functions I put into unmaintained.jl and UNMAINTAINED.md are either total mysteries to me, or they did not appear to fit into categories 1-3.

If you want to discuss their status further, I guess one of us could open an issue.

### CODE REVIEW

**Comment by maximsch2** [comment]
Thanks for the amazing work!

I'm not sure about those functions myself, so let's just keep them there in unmaintained. I agree with the idea of keeping them in a file as opposed to removing and relying in git to store them - this way someone might be able to land on them from google, fix them up and use them.

Travis failure on 0.6 seems to be related to DataFrames, so I'm fine with merging it once the OS X tests on Travis will pass.

**Comment by maximsch2** [comment]
One small thing: In Julia 0.6 you now have to write ```abs.(vec)``` instead of just ```abs(vec)```, the latter is deprecated. I've fixed those up in separate commit and confirmed that the package passes tests without errors or deprecation warnings on 0.6.

**Comment by joefowler** [comment]
Right! Thanks for the abs.() corrections. I guess those must have been your additions, but it didn't occur to me. At the time, I make a snap judgment that it was something left over from early Julia. Now I've been reading about the v0.6 changes and I get it.

I'm not sure what to do next. I think there are plenty of things that _could_ be done to rationalize the code organization and possibly fix/remove/add features, but I don't think any of that is necessary.

I think we should try to get this next version into METADATA. We could do that by getting the original author to accept a pull request (but we don't know if she is still interested), or we could ask the maintainers of METADATA to change the URL of this RobustStats.jl project. 

Do you have an opinion? I suppose the right thing would be to try a pull request first.

**Comment by maximsch2** [comment]
Sure, a pull-request sounds good.

Do you want to do it as you were the one who did most of the additional functionality and can better explain it?

**Pull request merged**
